### ISSUE TITLE
Fix URL of the "Edit" Link on Index Page

### ISSUE THREAD

**Issue by jessica-jordan** [ember-learn/guides-app#64] opened 2018-05-04 17:06 UTC
### Current
Currently the `Edit on Github` link on the index page doesn't link to the correct file on Github:

![guidesapp-no-edit-link](https://user-images.githubusercontent.com/8811742/39641107-5af62d8e-4fcd-11e8-9f86-582b1cf40e9a.gif)

### How to reproduce:
- visit https://emberguides.stonecircle.io/release/
- click pencil icon in upper right corner
-> the user is redirected to `https://github.com/ember-learn/guides-source/edit/master/guides/v3.1.0/index/.md`

### Expected
- if the user clicks the pencil icon in the upper right corner of the index page, they will be redirected to `https://github.com/ember-learn/guides-source/edit/master/guides/v3.1.0/index.md`

### Test stats:
Browser: Safari Version 11.1 
Domain: https://emberguides.stonecircle.io

**Comment by Stoobaart** [comment] 2018-05-17 18:25
I will attempt this as my first ever public contribution :D

**Comment by sivakumar-kailasam** [comment] 2018-05-17 18:28
@Stoobaart 👋 Go for it!

**Comment by Stoobaart** [comment] 2018-05-18 08:44
Hi @sivakumar-kailasam, 
I have investigated the issue and found that the problem is the data we get back from the backend, where the value return from "page.currentPage.url" is: 'index/' (The backslash is incorrect). I think that this should be fixed in the backend, so that the get request returns just 'index', unless this is the expected result and pertinent somewhere else this is being used. If it is, then I assume we would need to trim this in the guides app, but that, from my limited knowledge, seems a bit smelly.

**Comment by mansona** [comment] 2018-05-18 09:05
Hey @Stoobaart 👋 thanks for looking into this 🎉 

As it turns out we already had the right reference "in the backend" for this model 🎉 if you take a quick look at my PR you will see that I'm just moving over to using the id of the model instead of getting the URL from the Page service.

The Page service is specifically designed to create URLs that will work properly throughout the app, and the whole trailing slash problem is a bit hairy when you start going down that rabbit hole 🙈

**Closed** 2018-05-18 09:32 UTC
Labels: bug, good first issue

**Comment by sivakumar-kailasam** [comment] 2018-05-18 09:53
@Stoobaart As you can see we haven't levelled up on documenting this app as much as it could be. May be that's something you could help us with as you're going through this app. 
In case you'd like to work on something else apart from this, please feel free to reach out to me(slack handle: siva) or anyone from the learning team in #team-learning channel on [slack](https://ember-community-slackin.herokuapp.com/)

**Comment by Stoobaart** [comment] 2018-05-18 10:31
Hi @mansona and @sivakumar-kailasam,

Thanks so much for the answers! I did have a think about using the id key instead of the url key, and wasn't sure this would be the right way to go, as I thought that this would be more appropriate as a refactor in how all of the urls are generated throughout the app (beyond the scope of this ticket). I will make some time to go through the static site readme you suggested, and also have a think about the documentation as well. As I said, I am still really green (only been coding for about a year), but I am really interested in contributing to the community, especially as Ember is so go darn sweet. 

Cheers!

Stu

**Comment by mansona** [comment] 2018-05-18 11:17
@Stoobaart the fact that you are "still really green" is probably a really good reason for us to arrange a pairing session 😂 

Firstly it would hopefully help teach you a few things but also you should not undervalue your "beginner mindset". Some of us have been using Ember and building things like this for years and if you say something like "as a new developer I don't understand how X, Y or Z works" then that is **incredibly** useful feedback 🎉 

Sure reach out to us on the Slack and we can chat more about pairing if you would be interested 👍
